version: "3"

services:
  battleship_auth:
    image: battleship/game:${TAG:-latest}
    restart: unless-stopped
    links:
      - db
    ports:
      - 3000:3000
    environment:
      DB_HOST: 'db'
      DB_PORT: '3306'
      JWT_SECRET: ${BATTLESHIP_JWT_SECRET}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'battleship_web'
      # So you don't have to use root, but you can if you like
      #      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql

# Names our volume
volumes:
  db: